# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGV5wP3Wst_Ahkl9ZNC12Lt5nVUkmOHK
"""

# Step 1: Install dependencies
!pip install pandas numpy scipy ipywidgets gtts playsound -q

# Step 2: Imports
import pandas as pd
import numpy as np
from scipy.optimize import minimize
import ipywidgets as widgets
from IPython.display import display, clear_output, Audio, HTML
from datetime import datetime, timedelta
from gtts import gTTS
import os
import tempfile

# Step 3: Massively Expanded recipe dataset (200+ recipes from around the world)
recipes_data = [
    # ===== INDIAN CUISINE (40+ recipes) =====
    # Breakfast
    ["Masala Dosa", 350, 8, 10, 58, "vegan", "rice,lentils,potato,spices", 25, "breakfast,indian"],
    ["Idli with Sambar", 280, 10, 6, 48, "vegan", "rice,lentils,vegetables,spices", 20, "breakfast,indian"],
    ["Poha", 320, 8, 8, 55, "vegan", "flattened rice,peanuts,turmeric,vegetables", 15, "breakfast,indian,quick"],
    ["Upma", 300, 9, 7, 52, "vegan", "semolina,vegetables,mustard seeds,curry leaves", 15, "breakfast,indian,quick"],
    ["Paratha with Yogurt", 380, 12, 15, 48, "vegetarian", "wheat flour,ghee,yogurt,pickle", 20, "breakfast,indian"],
    ["Aloo Paratha", 420, 10, 16, 58, "vegetarian", "wheat flour,potato,ghee,yogurt", 25, "breakfast,indian"],
    ["Methi Thepla", 280, 8, 10, 42, "vegan", "wheat flour,fenugreek,spices", 20, "breakfast,indian"],
    ["Medu Vada", 250, 8, 12, 28, "vegan", "urad dal,curry leaves,coconut chutney", 20, "breakfast,indian"],
    ["Rava Uttapam", 310, 9, 8, 52, "vegetarian", "semolina,vegetables,yogurt", 18, "breakfast,indian"],

    # Lunch/Dinner
    ["Palak Paneer with Roti", 520, 22, 28, 45, "vegetarian", "spinach,paneer,roti,spices", 25, "lunch,dinner,indian"],
    ["Dal Tadka with Rice", 480, 18, 12, 75, "vegan", "lentils,rice,ghee,spices", 30, "lunch,dinner,indian"],
    ["Chole Bhature", 620, 16, 22, 85, "vegan", "chickpeas,flour,spices,oil", 35, "lunch,indian"],
    ["Rajma Chawal", 520, 18, 10, 88, "vegan", "kidney beans,rice,tomato,spices", 30, "lunch,dinner,indian"],
    ["Vegetable Biryani", 550, 14, 16, 85, "vegetarian", "basmati rice,vegetables,spices,ghee", 40, "lunch,dinner,indian"],
    ["Chicken Curry with Rice", 620, 42, 22, 58, "non-vegetarian", "chicken,rice,curry spices,coconut milk", 30, "lunch,dinner,indian"],
    ["Fish Curry", 420, 38, 18, 22, "non-vegetarian", "fish,coconut milk,curry leaves,spices", 25, "dinner,indian"],
    ["Paneer Bhurji with Roti", 540, 24, 30, 40, "vegetarian", "paneer,tomato,onion,spices", 20, "dinner,indian"],
    ["Chickpea Curry (Chana Masala)", 480, 18, 16, 65, "vegan", "chickpeas,tomato,onion,spices", 28, "lunch,dinner,indian"],
    ["Kadhi Pakora", 380, 14, 18, 42, "vegetarian", "gram flour,yogurt,pakora,spices", 30, "lunch,indian"],
    ["Aloo Gobi", 320, 8, 14, 45, "vegan", "potato,cauliflower,tomato,spices", 25, "lunch,dinner,indian"],
    ["Baingan Bharta", 280, 6, 16, 32, "vegan", "eggplant,onion,tomato,spices", 25, "dinner,indian"],
    ["Paneer Tikka Masala", 580, 28, 32, 38, "vegetarian", "paneer,cream,tomato,spices", 30, "dinner,indian"],
    ["Mutton Rogan Josh", 680, 45, 38, 28, "non-vegetarian", "mutton,yogurt,kashmiri spices", 45, "dinner,indian"],
    ["Butter Chicken", 620, 40, 32, 35, "non-vegetarian", "chicken,butter,cream,tomato", 35, "dinner,indian"],
    ["Prawn Masala", 420, 36, 20, 18, "non-vegetarian", "prawns,coconut,curry leaves,spices", 25, "dinner,indian"],
    ["Sambar Rice", 420, 14, 8, 72, "vegan", "rice,lentils,vegetables,tamarind", 30, "lunch,dinner,indian"],
    ["Pongal", 380, 12, 10, 65, "vegetarian", "rice,moong dal,ghee,pepper", 25, "breakfast,indian"],
    ["Kofta Curry", 520, 20, 28, 45, "vegetarian", "vegetable balls,tomato gravy,cream", 35, "dinner,indian"],

    # Snacks
    ["Samosa", 320, 6, 16, 40, "vegan", "potato,peas,flour,spices", 30, "snack,indian"],
    ["Pakora", 280, 8, 14, 32, "vegan", "gram flour,vegetables,spices", 20, "snack,indian"],
    ["Dhokla", 180, 6, 4, 32, "vegan", "gram flour,yogurt,mustard seeds", 25, "snack,indian"],
    ["Bhel Puri", 220, 6, 8, 32, "vegan", "puffed rice,sev,tamarind,vegetables", 10, "snack,indian,quick"],
    ["Paneer Tikka", 320, 24, 18, 12, "vegetarian", "paneer,yogurt,spices", 25, "snack,indian"],

    # ===== CHINESE CUISINE (25+ recipes) =====
    ["Vegetable Fried Rice", 420, 12, 14, 62, "vegan", "rice,mixed vegetables,soy sauce,sesame oil", 15, "lunch,dinner,chinese,quick"],
    ["Chicken Fried Rice", 540, 32, 18, 58, "non-vegetarian", "chicken,rice,egg,vegetables,soy sauce", 20, "lunch,dinner,chinese"],
    ["Tofu Stir Fry", 380, 22, 16, 38, "vegan", "tofu,bok choy,ginger,soy sauce", 18, "lunch,dinner,chinese,quick"],
    ["Kung Pao Chicken", 480, 36, 22, 32, "non-vegetarian", "chicken,peanuts,vegetables,chili", 20, "dinner,chinese"],
    ["Mapo Tofu", 420, 20, 24, 28, "vegan", "tofu,sichuan pepper,fermented beans,scallions", 20, "dinner,chinese"],
    ["Egg Drop Soup", 120, 10, 5, 8, "vegetarian", "egg,chicken broth,cornstarch,scallions", 10, "snack,soup,chinese,quick"],
    ["Spring Rolls", 280, 8, 12, 36, "vegan", "rice paper,vegetables,vermicelli,soy sauce", 15, "snack,chinese"],
    ["Sweet and Sour Chicken", 520, 32, 18, 58, "non-vegetarian", "chicken,bell peppers,pineapple,sauce", 25, "dinner,chinese"],
    ["Szechuan Beef", 580, 40, 28, 38, "non-vegetarian", "beef,vegetables,szechuan sauce", 20, "dinner,chinese"],
    ["Chow Mein", 480, 16, 16, 68, "vegan", "noodles,vegetables,soy sauce", 18, "lunch,dinner,chinese"],
    ["Hot and Sour Soup", 140, 10, 6, 12, "non-vegetarian", "tofu,mushrooms,vinegar,egg", 15, "snack,soup,chinese"],
    ["General Tso's Tofu", 450, 22, 20, 48, "vegan", "tofu,vegetables,sweet spicy sauce", 25, "dinner,chinese"],
    ["Steamed Dumplings", 320, 14, 12, 38, "non-vegetarian", "dumpling wrapper,pork,vegetables", 30, "lunch,snack,chinese"],
    ["Lo Mein", 520, 18, 18, 68, "vegan", "noodles,vegetables,soy sauce,sesame", 20, "lunch,dinner,chinese"],
    ["Mongolian Beef", 560, 38, 26, 42, "non-vegetarian", "beef,scallions,ginger,garlic", 22, "dinner,chinese"],

    # ===== JAPANESE CUISINE (20+ recipes) =====
    ["Miso Soup", 120, 8, 4, 12, "vegan", "miso paste,tofu,seaweed,scallion", 10, "snack,soup,japanese,quick"],
    ["Chicken Teriyaki Bowl", 580, 38, 18, 62, "non-vegetarian", "chicken,rice,teriyaki sauce,vegetables", 25, "lunch,dinner,japanese"],
    ["Salmon Sushi Bowl", 520, 36, 20, 48, "non-vegetarian", "salmon,sushi rice,avocado,seaweed", 20, "lunch,dinner,japanese"],
    ["Tofu Teriyaki", 380, 24, 16, 38, "vegan", "tofu,teriyaki sauce,sesame seeds,vegetables", 18, "lunch,dinner,japanese"],
    ["Vegetable Tempura", 320, 8, 15, 38, "vegetarian", "mixed vegetables,tempura batter,dipping sauce", 20, "lunch,snack,japanese"],
    ["Edamame", 180, 16, 8, 14, "vegan", "soybeans,sea salt", 5, "snack,japanese,quick"],
    ["Ramen Bowl", 520, 24, 18, 62, "non-vegetarian", "noodles,broth,egg,pork,vegetables", 30, "lunch,dinner,japanese"],
    ["Katsu Curry", 680, 32, 28, 72, "non-vegetarian", "breaded pork,curry sauce,rice", 35, "dinner,japanese"],
    ["Gyoza", 280, 14, 12, 28, "non-vegetarian", "dumpling wrapper,pork,cabbage", 25, "snack,japanese"],
    ["Yakitori", 320, 38, 14, 8, "non-vegetarian", "chicken skewers,teriyaki glaze", 20, "dinner,snack,japanese"],
    ["Okonomiyaki", 420, 18, 20, 42, "non-vegetarian", "cabbage,flour,egg,toppings", 25, "lunch,dinner,japanese"],
    ["Tonkatsu", 620, 36, 32, 48, "non-vegetarian", "breaded pork,cabbage,tonkatsu sauce", 30, "dinner,japanese"],

    # ===== MEDITERRANEAN/MIDDLE EASTERN (25+ recipes) =====
    ["Hummus with Veggies", 220, 8, 12, 22, "vegan", "chickpeas,tahini,carrot,cucumber", 5, "snack,mediterranean,quick"],
    ["Greek Salad", 280, 8, 18, 18, "vegetarian", "feta,cucumber,tomato,olives,olive oil", 10, "lunch,salad,mediterranean,quick"],
    ["Falafel Wrap", 480, 16, 20, 58, "vegan", "falafel,pita,tahini,vegetables", 15, "lunch,mediterranean"],
    ["Grilled Chicken Shawarma", 520, 42, 22, 38, "non-vegetarian", "chicken,pita,tahini,vegetables", 25, "lunch,dinner,mediterranean"],
    ["Tabbouleh", 180, 6, 8, 24, "vegan", "bulgur wheat,parsley,tomato,lemon,olive oil", 15, "snack,salad,mediterranean"],
    ["Shakshuka", 320, 18, 20, 18, "vegetarian", "eggs,tomato,peppers,cumin,paprika", 20, "breakfast,mediterranean"],
    ["Lamb Kebab with Rice", 620, 40, 28, 48, "non-vegetarian", "lamb,rice,spices,vegetables", 30, "dinner,mediterranean"],
    ["Baba Ganoush", 180, 4, 12, 18, "vegan", "eggplant,tahini,lemon,garlic", 25, "snack,mediterranean"],
    ["Stuffed Grape Leaves", 220, 6, 10, 28, "vegan", "grape leaves,rice,herbs,lemon", 30, "snack,mediterranean"],
    ["Moussaka", 520, 24, 28, 42, "non-vegetarian", "eggplant,ground beef,bechamel", 45, "dinner,mediterranean"],
    ["Turkish Pide", 480, 20, 18, 58, "non-vegetarian", "flatbread,ground meat,cheese", 30, "lunch,dinner,mediterranean"],
    ["Couscous Salad", 380, 12, 14, 52, "vegan", "couscous,vegetables,lemon,olive oil", 15, "lunch,salad,mediterranean"],
    ["Chicken Souvlaki", 420, 40, 18, 22, "non-vegetarian", "chicken skewers,tzatziki,pita", 25, "dinner,mediterranean"],
    ["Spanakopita", 380, 14, 22, 32, "vegetarian", "spinach,feta,phyllo dough", 35, "lunch,mediterranean"],

    # ===== ITALIAN CUISINE (25+ recipes) =====
    ["Margherita Pizza", 520, 20, 18, 62, "vegetarian", "dough,mozzarella,tomato,basil", 25, "lunch,dinner,italian"],
    ["Pasta Primavera", 480, 16, 14, 72, "vegetarian", "pasta,vegetables,olive oil,parmesan", 20, "lunch,dinner,italian"],
    ["Chicken Alfredo Pasta", 780, 42, 32, 72, "non-vegetarian", "chicken,pasta,cream,parmesan", 25, "dinner,italian"],
    ["Caprese Salad", 240, 12, 16, 12, "vegetarian", "mozzarella,tomato,basil,olive oil", 5, "lunch,salad,italian,quick"],
    ["Veggie Lasagna", 580, 26, 24, 62, "vegetarian", "pasta,ricotta,spinach,tomato sauce", 35, "dinner,italian"],
    ["Minestrone Soup", 220, 10, 6, 32, "vegan", "vegetables,beans,pasta,tomato", 25, "lunch,soup,italian"],
    ["Mushroom Risotto", 520, 16, 18, 68, "vegetarian", "arborio rice,mushrooms,parmesan,butter", 35, "dinner,italian"],
    ["Spaghetti Carbonara", 620, 28, 28, 68, "non-vegetarian", "pasta,eggs,bacon,parmesan", 20, "dinner,italian"],
    ["Penne Arrabbiata", 420, 14, 12, 68, "vegan", "pasta,tomato,garlic,chili", 20, "lunch,dinner,italian"],
    ["Bruschetta", 220, 6, 8, 32, "vegan", "bread,tomato,basil,garlic", 10, "snack,italian,quick"],
    ["Eggplant Parmesan", 480, 20, 24, 48, "vegetarian", "eggplant,tomato sauce,mozzarella", 35, "dinner,italian"],
    ["Gnocchi with Pesto", 520, 16, 22, 62, "vegetarian", "potato gnocchi,basil pesto,parmesan", 20, "lunch,dinner,italian"],
    ["Osso Buco", 680, 48, 32, 38, "non-vegetarian", "veal shanks,vegetables,wine", 120, "dinner,italian"],

    # ===== MEXICAN CUISINE (20+ recipes) =====
    ["Black Bean Tacos", 520, 20, 16, 68, "vegan", "black beans,corn tortilla,avocado,salsa", 20, "lunch,dinner,mexican"],
    ["Chicken Burrito Bowl", 620, 38, 22, 62, "non-vegetarian", "chicken,rice,beans,cheese,guacamole", 20, "lunch,dinner,mexican"],
    ["Vegetarian Enchiladas", 540, 22, 20, 58, "vegetarian", "tortilla,cheese,beans,enchilada sauce", 30, "dinner,mexican"],
    ["Cheese Quesadilla", 480, 20, 24, 42, "vegetarian", "tortilla,cheese,peppers,salsa", 12, "lunch,mexican,quick"],
    ["Guacamole with Chips", 320, 6, 22, 28, "vegan", "avocado,lime,cilantro,tortilla chips", 8, "snack,mexican,quick"],
    ["Chicken Fajitas", 520, 40, 20, 42, "non-vegetarian", "chicken,peppers,onions,tortilla", 25, "dinner,mexican"],
    ["Chile Relleno", 420, 18, 24, 32, "vegetarian", "poblano pepper,cheese,egg batter", 30, "dinner,mexican"],
    ["Pozole", 420, 28, 12, 48, "non-vegetarian", "pork,hominy,chili,cabbage", 90, "lunch,dinner,mexican"],
    ["Tamales", 380, 14, 16, 45, "non-vegetarian", "masa,pork,corn husk", 60, "lunch,dinner,mexican"],
    ["Mexican Rice", 280, 6, 8, 48, "vegan", "rice,tomato,onion,peppers", 20, "lunch,dinner,mexican"],

    # ===== THAI CUISINE (15+ recipes) =====
    ["Pad Thai", 580, 20, 18, 78, "non-vegetarian", "rice noodles,shrimp,egg,tamarind,peanuts", 25, "lunch,dinner,thai"],
    ["Green Curry with Rice", 520, 16, 24, 62, "vegan", "vegetables,coconut milk,green curry paste,rice", 25, "dinner,thai"],
    ["Tom Yum Soup", 180, 12, 6, 18, "non-vegetarian", "shrimp,lemongrass,lime,mushrooms", 20, "snack,soup,thai"],
    ["Thai Basil Chicken", 480, 36, 20, 38, "non-vegetarian", "chicken,basil,chili,soy sauce", 18, "dinner,thai,quick"],
    ["Massaman Curry", 580, 24, 28, 58, "non-vegetarian", "chicken,potato,peanuts,coconut milk", 30, "dinner,thai"],
    ["Papaya Salad", 180, 4, 6, 28, "vegan", "green papaya,tomato,peanuts,lime", 15, "snack,salad,thai"],
    ["Pad See Ew", 520, 18, 16, 72, "non-vegetarian", "wide noodles,chicken,broccoli,soy", 20, "lunch,dinner,thai"],

    # ===== AMERICAN/WESTERN (25+ recipes) =====
    # Breakfast
    ["Oatmeal with Banana", 350, 10, 5, 60, "vegetarian", "oats,banana,milk,honey", 10, "breakfast,american,quick"],
    ["Greek Yogurt Parfait", 320, 18, 8, 42, "vegetarian", "greek yogurt,granola,berries,honey", 5, "breakfast,american,quick"],
    ["Egg Omelette with Veggies", 300, 18, 20, 8, "non-vegetarian", "eggs,peppers,onion,tomato", 10, "breakfast,american,quick"],
    ["Avocado Toast", 380, 12, 18, 42, "vegan", "whole wheat bread,avocado,tomato,seeds", 8, "breakfast,american,quick"],
    ["Protein Pancakes", 420, 24, 12, 48, "vegetarian", "oats,egg,banana,protein powder", 15, "breakfast,american"],
    ["Egg White Omelette", 220, 24, 6, 4, "non-vegetarian", "egg whites,spinach,mushroom", 10, "breakfast,american,quick"],
    ["Bagel with Cream Cheese", 380, 14, 12, 56, "vegetarian", "bagel,cream cheese,tomato", 5, "breakfast,american,quick"],
    ["French Toast", 420, 14, 16, 58, "vegetarian", "bread,egg,milk,maple syrup", 15, "breakfast,american"],
    ["Breakfast Burrito", 520, 24, 22, 52, "non-vegetarian", "tortilla,eggs,cheese,sausage", 15, "breakfast,american"],

    # Lunch/Dinner
    ["Grilled Chicken Breast", 380, 45, 12, 5, "non-vegetarian", "chicken breast,herbs,olive oil", 20, "lunch,dinner,american"],
    ["Turkey Wrap", 450, 30, 16, 40, "non-vegetarian", "turkey,tortilla,lettuce,hummus", 10, "lunch,american,quick"],
    ["Chicken Salad", 420, 35, 15, 25, "non-vegetarian", "chicken,lettuce,tomato,olive oil", 15, "lunch,salad,american"],
    ["Beef Stir Fry", 520, 42, 26, 28, "non-vegetarian", "beef,vegetables,soy sauce", 20, "dinner,american"],
    ["Grilled Fish with Veggies", 460, 40, 25, 10, "non-vegetarian", "fish,broccoli,carrot,olive oil", 25, "dinner,american"],
    ["Salmon with Quinoa", 540, 38, 24, 42, "non-vegetarian", "salmon,quinoa,asparagus,lemon", 25, "dinner,american"],
    ["BBQ Chicken Wings", 480, 42, 28, 12, "non-vegetarian", "chicken wings,bbq sauce,celery", 30, "dinner,snack,american"],
    ["Loaded Sweet Potato", 620, 18, 28, 78, "vegetarian", "sweet potato,cheese,sour cream,beans", 30, "lunch,dinner,american"],
    ["Caesar Salad", 380, 22, 24, 18, "non-vegetarian", "romaine,chicken,parmesan,caesar dressing", 10, "lunch,salad,american"],
    ["Mac and Cheese", 520, 20, 24, 58, "vegetarian", "pasta,cheddar,milk,butter", 20, "lunch,dinner,american"],
    ["Pot Roast", 680, 48, 38, 32, "non-vegetarian", "beef roast,potatoes,carrots,gravy", 180, "dinner,american"],

    # Snacks
    ["Veg Sandwich", 290, 9, 12, 36, "vegetarian", "bread,lettuce,cucumber,tomato", 8, "snack,american,quick"],
    ["Cottage Cheese Bowl", 280, 28, 8, 18, "vegetarian", "cottage cheese,berries,honey", 5, "snack,american,quick"],
    ["Mixed Nuts", 320, 10, 28, 12, "vegan", "almonds,cashews,walnuts", 1, "snack,american,quick"],
    ["Apple with Peanut Butter", 280, 8, 16, 32, "vegan", "apple,peanut butter", 2, "snack,american,quick"],
    ["Protein Shake", 280, 25, 6, 28, "vegetarian", "whey protein,banana,almond milk", 3, "snack,drink,american,quick"],
    ["Fruit Smoothie", 250, 6, 4, 50, "vegetarian", "milk,banana,berries,honey", 5, "snack,drink,american,quick"],
    ["Peanut Butter Banana Smoothie", 520, 18, 20, 68, "vegetarian", "banana,peanut butter,oats,milk", 5, "snack,drink,american"],

    # ===== AFRICAN CUISINE (15+ recipes) =====
    ["Jollof Rice", 480, 14, 16, 72, "vegan", "rice,tomato,peppers,onions,spices", 30, "lunch,dinner,african"],
    ["Fufu with Egusi Soup", 520, 18, 22, 62, "vegetarian", "cassava,melon seeds,spinach,palm oil", 35, "dinner,african"],
    ["Moroccan Couscous", 420, 14, 12, 68, "vegan", "couscous,vegetables,chickpeas,raisins", 25, "lunch,dinner,african"],
    ["Injera with Wat", 380, 14, 10, 65, "vegan", "teff flour,lentils,spices", 30, "lunch,dinner,african"],
    ["Bobotie", 580, 32, 28, 42, "non-vegetarian", "ground beef,curry,egg,bread", 45, "dinner,african"],
    ["Bunny Chow", 620, 24, 18, 88, "non-vegetarian", "bread loaf,curry,chicken", 35, "lunch,dinner,african"],
    ["Suya", 420, 38, 22, 12, "non-vegetarian", "beef skewers,peanut spice,onions", 25, "dinner,snack,african"],
    ["Piri Piri Chicken", 520, 42, 26, 18, "non-vegetarian", "chicken,piri piri sauce,vegetables", 30, "dinner,african"],

    # ===== KOREAN CUISINE (15+ recipes) =====
    ["Bibimbap", 580, 24, 18, 78, "non-vegetarian", "rice,vegetables,egg,gochujang,beef", 25, "lunch,dinner,korean"],
    ["Kimchi Fried Rice", 420, 16, 14, 58, "vegan", "rice,kimchi,vegetables,sesame oil", 15, "lunch,dinner,korean,quick"],
    ["Korean BBQ Tofu", 380, 22, 18, 32, "vegan", "tofu,gochujang,sesame,vegetables", 20, "dinner,korean"],
    ["Bulgogi", 520, 38, 22, 38, "non-vegetarian", "beef,marinade,vegetables,rice", 30, "dinner,korean"],
    ["Kimchi Jjigae", 320, 20, 16, 28, "non-vegetarian", "kimchi,pork,tofu,broth", 25, "lunch,dinner,korean"],
    ["Japchae", 420, 14, 12, 68, "vegan", "glass noodles,vegetables,soy sauce", 25, "lunch,dinner,korean"],
    ["Korean Fried Chicken", 620, 38, 32, 48, "non-vegetarian", "chicken,gochujang glaze", 35, "dinner,korean"],

    # ===== VIETNAMESE CUISINE (12+ recipes) =====
    ["Pho (Beef Noodle Soup)", 420, 28, 8, 58, "non-vegetarian", "rice noodles,beef,broth,herbs", 25, "lunch,dinner,vietnamese"],
    ["Banh Mi Sandwich", 480, 22, 18, 52, "non-vegetarian", "baguette,pork,pickled vegetables,cilantro", 15, "lunch,vietnamese"],
    ["Vietnamese Spring Rolls", 220, 12, 6, 32, "non-vegetarian", "rice paper,shrimp,vermicelli,vegetables", 15, "snack,vietnamese"],
    ["Bun Cha", 520, 32, 20, 48, "non-vegetarian", "grilled pork,noodles,herbs,fish sauce", 30, "lunch,dinner,vietnamese"],
    ["Com Tam", 580, 28, 22, 62, "non-vegetarian", "broken rice,grilled pork,egg,pickles", 25, "lunch,dinner,vietnamese"],

    # ===== SOUTH AMERICAN CUISINE (10+ recipes) =====
    ["Brazilian Feijoada", 580, 32, 24, 52, "non-vegetarian", "black beans,pork,rice,collard greens", 40, "dinner,brazilian"],
    ["Argentinian Empanadas", 420, 18, 20, 42, "non-vegetarian", "dough,beef,onions,spices", 30, "lunch,snack,argentinian"],
    ["Peruvian Ceviche", 280, 32, 8, 18, "non-vegetarian", "fish,lime,onion,cilantro", 20, "lunch,snack,peruvian"],
    ["Arroz con Pollo", 580, 36, 18, 62, "non-vegetarian", "chicken,rice,vegetables,saffron", 35, "dinner,latin"],

    # ===== UNIVERSAL/FUSION (15+ recipes) =====
    ["Buddha Bowl", 550, 18, 22, 68, "vegan", "quinoa,chickpeas,avocado,kale,tahini", 25, "lunch,dinner"],
    ["Quinoa Chickpea Salad", 520, 20, 18, 60, "vegan", "quinoa,chickpeas,tomato,cucumber,olive oil", 20, "lunch,salad"],
    ["Lentil Soup", 380, 22, 9, 45, "vegan", "lentils,carrot,onion,spices", 20, "lunch,soup"],
    ["Scrambled Tofu", 290, 16, 14, 25, "vegan", "tofu,turmeric,spinach,onion", 12, "breakfast"],]
# Advanced AI-Driven Personalized Diet Plan Generator
# With Feedback System & Health Improvement Suggestions
# ============================================

# Step 3: Expanded recipe dataset (100+ recipes from around the world)
recipes_data = [
    # ===== INDIAN CUISINE =====
    # Breakfast
    ["Masala Dosa", 350, 8, 10, 58, "vegan", "rice,lentils,potato,spices", 25, "breakfast,indian"],
    ["Idli with Sambar", 280, 10, 6, 48, "vegan", "rice,lentils,vegetables,spices", 20, "breakfast,indian"],
    ["Poha", 320, 8, 8, 55, "vegan", "flattened rice,peanuts,turmeric,vegetables", 15, "breakfast,indian,quick"],
    ["Upma", 300, 9, 7, 52, "vegan", "semolina,vegetables,mustard seeds,curry leaves", 15, "breakfast,indian,quick"],
    ["Paratha with Yogurt", 380, 12, 15, 48, "vegetarian", "wheat flour,ghee,yogurt,pickle", 20, "breakfast,indian"],

    # Lunch/Dinner
    ["Palak Paneer with Roti", 520, 22, 28, 45, "vegetarian", "spinach,paneer,roti,spices", 25, "lunch,dinner,indian"],
    ["Dal Tadka with Rice", 480, 18, 12, 75, "vegan", "lentils,rice,ghee,spices", 30, "lunch,dinner,indian"],
    ["Chole Bhature", 620, 16, 22, 85, "vegan", "chickpeas,flour,spices,oil", 35, "lunch,indian"],
    ["Rajma Chawal", 520, 18, 10, 88, "vegan", "kidney beans,rice,tomato,spices", 30, "lunch,dinner,indian"],
    ["Vegetable Biryani", 550, 14, 16, 85, "vegetarian", "basmati rice,vegetables,spices,ghee", 40, "lunch,dinner,indian"],
    ["Chicken Curry with Rice", 620, 42, 22, 58, "non-vegetarian", "chicken,rice,curry spices,coconut milk", 30, "lunch,dinner,indian"],
    ["Fish Curry", 420, 38, 18, 22, "non-vegetarian", "fish,coconut milk,curry leaves,spices", 25, "dinner,indian"],
    ["Paneer Bhurji with Roti", 540, 24, 30, 40, "vegetarian", "paneer,tomato,onion,spices", 20, "dinner,indian"],
    ["Chickpea Curry (Chana Masala)", 480, 18, 16, 65, "vegan", "chickpeas,tomato,onion,spices", 28, "lunch,dinner,indian"],

    # ===== CHINESE CUISINE =====
    ["Vegetable Fried Rice", 420, 12, 14, 62, "vegan", "rice,mixed vegetables,soy sauce,sesame oil", 15, "lunch,dinner,chinese,quick"],
    ["Chicken Fried Rice", 540, 32, 18, 58, "non-vegetarian", "chicken,rice,egg,vegetables,soy sauce", 20, "lunch,dinner,chinese"],
    ["Tofu Stir Fry", 380, 22, 16, 38, "vegan", "tofu,bok choy,ginger,soy sauce", 18, "lunch,dinner,chinese,quick"],
    ["Kung Pao Chicken", 480, 36, 22, 32, "non-vegetarian", "chicken,peanuts,vegetables,chili", 20, "dinner,chinese"],
    ["Mapo Tofu", 420, 20, 24, 28, "vegan", "tofu,sichuan pepper,fermented beans,scallions", 20, "dinner,chinese"],
    ["Egg Drop Soup", 120, 10, 5, 8, "vegetarian", "egg,chicken broth,cornstarch,scallions", 10, "snack,soup,chinese,quick"],
    ["Spring Rolls", 280, 8, 12, 36, "vegan", "rice paper,vegetables,vermicelli,soy sauce", 15, "snack,chinese"],

    # ===== JAPANESE CUISINE =====
    ["Miso Soup", 120, 8, 4, 12, "vegan", "miso paste,tofu,seaweed,scallion", 10, "snack,soup,japanese,quick"],
    ["Chicken Teriyaki Bowl", 580, 38, 18, 62, "non-vegetarian", "chicken,rice,teriyaki sauce,vegetables", 25, "lunch,dinner,japanese"],
    ["Salmon Sushi Bowl", 520, 36, 20, 48, "non-vegetarian", "salmon,sushi rice,avocado,seaweed", 20, "lunch,dinner,japanese"],
    ["Tofu Teriyaki", 380, 24, 16, 38, "vegan", "tofu,teriyaki sauce,sesame seeds,vegetables", 18, "lunch,dinner,japanese"],
    ["Vegetable Tempura", 320, 8, 15, 38, "vegetarian", "mixed vegetables,tempura batter,dipping sauce", 20, "lunch,snack,japanese"],
    ["Edamame", 180, 16, 8, 14, "vegan", "soybeans,sea salt", 5, "snack,japanese,quick"],

    # ===== MEDITERRANEAN/MIDDLE EASTERN =====
    ["Hummus with Veggies", 220, 8, 12, 22, "vegan", "chickpeas,tahini,carrot,cucumber", 5, "snack,mediterranean,quick"],
    ["Greek Salad", 280, 8, 18, 18, "vegetarian", "feta,cucumber,tomato,olives,olive oil", 10, "lunch,salad,mediterranean,quick"],
    ["Falafel Wrap", 480, 16, 20, 58, "vegan", "falafel,pita,tahini,vegetables", 15, "lunch,mediterranean"],
    ["Grilled Chicken Shawarma", 520, 42, 22, 38, "non-vegetarian", "chicken,pita,tahini,vegetables", 25, "lunch,dinner,mediterranean"],
    ["Tabbouleh", 180, 6, 8, 24, "vegan", "bulgur wheat,parsley,tomato,lemon,olive oil", 15, "snack,salad,mediterranean"],
    ["Shakshuka", 320, 18, 20, 18, "vegetarian", "eggs,tomato,peppers,cumin,paprika", 20, "breakfast,mediterranean"],
    ["Lamb Kebab with Rice", 620, 40, 28, 48, "non-vegetarian", "lamb,rice,spices,vegetables", 30, "dinner,mediterranean"],

    # ===== ITALIAN CUISINE =====
    ["Margherita Pizza", 520, 20, 18, 62, "vegetarian", "dough,mozzarella,tomato,basil", 25, "lunch,dinner,italian"],
    ["Pasta Primavera", 480, 16, 14, 72, "vegetarian", "pasta,vegetables,olive oil,parmesan", 20, "lunch,dinner,italian"],
    ["Chicken Alfredo Pasta", 780, 42, 32, 72, "non-vegetarian", "chicken,pasta,cream,parmesan", 25, "dinner,italian"],
    ["Caprese Salad", 240, 12, 16, 12, "vegetarian", "mozzarella,tomato,basil,olive oil", 5, "lunch,salad,italian,quick"],
    ["Veggie Lasagna", 580, 26, 24, 62, "vegetarian", "pasta,ricotta,spinach,tomato sauce", 35, "dinner,italian"],
    ["Minestrone Soup", 220, 10, 6, 32, "vegan", "vegetables,beans,pasta,tomato", 25, "lunch,soup,italian"],
    ["Mushroom Risotto", 520, 16, 18, 68, "vegetarian", "arborio rice,mushrooms,parmesan,butter", 35, "dinner,italian"],

    # ===== MEXICAN CUISINE =====
    ["Black Bean Tacos", 520, 20, 16, 68, "vegan", "black beans,corn tortilla,avocado,salsa", 20, "lunch,dinner,mexican"],
    ["Chicken Burrito Bowl", 620, 38, 22, 62, "non-vegetarian", "chicken,rice,beans,cheese,guacamole", 20, "lunch,dinner,mexican"],
    ["Vegetarian Enchiladas", 540, 22, 20, 58, "vegetarian", "tortilla,cheese,beans,enchilada sauce", 30, "dinner,mexican"],
    ["Cheese Quesadilla", 480, 20, 24, 42, "vegetarian", "tortilla,cheese,peppers,salsa", 12, "lunch,mexican,quick"],
    ["Guacamole with Chips", 320, 6, 22, 28, "vegan", "avocado,lime,cilantro,tortilla chips", 8, "snack,mexican,quick"],

    # ===== THAI CUISINE =====
    ["Pad Thai", 580, 20, 18, 78, "non-vegetarian", "rice noodles,shrimp,egg,tamarind,peanuts", 25, "lunch,dinner,thai"],
    ["Green Curry with Rice", 520, 16, 24, 62, "vegan", "vegetables,coconut milk,green curry paste,rice", 25, "dinner,thai"],
    ["Tom Yum Soup", 180, 12, 6, 18, "non-vegetarian", "shrimp,lemongrass,lime,mushrooms", 20, "snack,soup,thai"],
    ["Thai Basil Chicken", 480, 36, 20, 38, "non-vegetarian", "chicken,basil,chili,soy sauce", 18, "dinner,thai,quick"],

    # ===== AMERICAN/WESTERN =====
    # Breakfast
    ["Oatmeal with Banana", 350, 10, 5, 60, "vegetarian", "oats,banana,milk,honey", 10, "breakfast,american,quick"],
    ["Greek Yogurt Parfait", 320, 18, 8, 42, "vegetarian", "greek yogurt,granola,berries,honey", 5, "breakfast,american,quick"],
    ["Egg Omelette with Veggies", 300, 18, 20, 8, "non-vegetarian", "eggs,peppers,onion,tomato", 10, "breakfast,american,quick"],
    ["Avocado Toast", 380, 12, 18, 42, "vegan", "whole wheat bread,avocado,tomato,seeds", 8, "breakfast,american,quick"],
    ["Protein Pancakes", 420, 24, 12, 48, "vegetarian", "oats,egg,banana,protein powder", 15, "breakfast,american"],
    ["Egg White Omelette", 220, 24, 6, 4, "non-vegetarian", "egg whites,spinach,mushroom", 10, "breakfast,american,quick"],
    ["Bagel with Cream Cheese", 380, 14, 12, 56, "vegetarian", "bagel,cream cheese,tomato", 5, "breakfast,american,quick"],

    # Lunch/Dinner
    ["Grilled Chicken Breast", 380, 45, 12, 5, "non-vegetarian", "chicken breast,herbs,olive oil", 20, "lunch,dinner,american"],
    ["Turkey Wrap", 450, 30, 16, 40, "non-vegetarian", "turkey,tortilla,lettuce,hummus", 10, "lunch,american,quick"],
    ["Chicken Salad", 420, 35, 15, 25, "non-vegetarian", "chicken,lettuce,tomato,olive oil", 15, "lunch,salad,american"],
    ["Beef Stir Fry", 520, 42, 26, 28, "non-vegetarian", "beef,vegetables,soy sauce", 20, "dinner,american"],
    ["Grilled Fish with Veggies", 460, 40, 25, 10, "non-vegetarian", "fish,broccoli,carrot,olive oil", 25, "dinner,american"],
    ["Salmon with Quinoa", 540, 38, 24, 42, "non-vegetarian", "salmon,quinoa,asparagus,lemon", 25, "dinner,american"],
    ["BBQ Chicken Wings", 480, 42, 28, 12, "non-vegetarian", "chicken wings,bbq sauce,celery", 30, "dinner,snack,american"],
    ["Loaded Sweet Potato", 620, 18, 28, 78, "vegetarian", "sweet potato,cheese,sour cream,beans", 30, "lunch,dinner,american"],

    # Snacks
    ["Veg Sandwich", 290, 9, 12, 36, "vegetarian", "bread,lettuce,cucumber,tomato", 8, "snack,american,quick"],
    ["Cottage Cheese Bowl", 280, 28, 8, 18, "vegetarian", "cottage cheese,berries,honey", 5, "snack,american,quick"],
    ["Mixed Nuts", 320, 10, 28, 12, "vegan", "almonds,cashews,walnuts", 1, "snack,american,quick"],
    ["Apple with Peanut Butter", 280, 8, 16, 32, "vegan", "apple,peanut butter", 2, "snack,american,quick"],
    ["Protein Shake", 280, 25, 6, 28, "vegetarian", "whey protein,banana,almond milk", 3, "snack,drink,american,quick"],
    ["Fruit Smoothie", 250, 6, 4, 50, "vegetarian", "milk,banana,berries,honey", 5, "snack,drink,american,quick"],
    ["Peanut Butter Banana Smoothie", 520, 18, 20, 68, "vegetarian", "banana,peanut butter,oats,milk", 5, "snack,drink,american"],

    # ===== AFRICAN CUISINE =====
    ["Jollof Rice", 480, 14, 16, 72, "vegan", "rice,tomato,peppers,onions,spices", 30, "lunch,dinner,african"],
    ["Fufu with Egusi Soup", 520, 18, 22, 62, "vegetarian", "cassava,melon seeds,spinach,palm oil", 35, "dinner,african"],
    ["Moroccan Couscous", 420, 14, 12, 68, "vegan", "couscous,vegetables,chickpeas,raisins", 25, "lunch,dinner,african"],

    # ===== KOREAN CUISINE =====
    ["Bibimbap", 580, 24, 18, 78, "non-vegetarian", "rice,vegetables,egg,gochujang,beef", 25, "lunch,dinner,korean"],
    ["Kimchi Fried Rice", 420, 16, 14, 58, "vegan", "rice,kimchi,vegetables,sesame oil", 15, "lunch,dinner,korean,quick"],
    ["Korean BBQ Tofu", 380, 22, 18, 32, "vegan", "tofu,gochujang,sesame,vegetables", 20, "dinner,korean"],

    # ===== VIETNAMESE CUISINE =====
    ["Pho (Beef Noodle Soup)", 420, 28, 8, 58, "non-vegetarian", "rice noodles,beef,broth,herbs", 25, "lunch,dinner,vietnamese"],
    ["Banh Mi Sandwich", 480, 22, 18, 52, "non-vegetarian", "baguette,pork,pickled vegetables,cilantro", 15, "lunch,vietnamese"],
    ["Vietnamese Spring Rolls", 220, 12, 6, 32, "non-vegetarian", "rice paper,shrimp,vermicelli,vegetables", 15, "snack,vietnamese"],

    # ===== SOUTH AMERICAN CUISINE =====
    ["Brazilian Feijoada", 580, 32, 24, 52, "non-vegetarian", "black beans,pork,rice,collard greens", 40, "dinner,brazilian"],
    ["Argentinian Empanadas", 420, 18, 20, 42, "non-vegetarian", "dough,beef,onions,spices", 30, "lunch,snack,argentinian"],

    # ===== UNIVERSAL/FUSION =====
    ["Buddha Bowl", 550, 18, 22, 68, "vegan", "quinoa,chickpeas,avocado,kale,tahini", 25, "lunch,dinner"],
    ["Quinoa Chickpea Salad", 520, 20, 18, 60, "vegan", "quinoa,chickpeas,tomato,cucumber,olive oil", 20, "lunch,salad"],
    ["Lentil Soup", 380, 22, 9, 45, "vegan", "lentils,carrot,onion,spices", 20, "lunch,soup"],
    ["Scrambled Tofu", 290, 16, 14, 25, "vegan", "tofu,turmeric,spinach,onion", 12, "breakfast"],
    ["Chia Pudding", 280, 8, 12, 38, "vegan", "chia seeds,almond milk,berries,maple syrup", 5, "breakfast,quick"],
    ["Tempeh Sandwich", 420, 22, 18, 42, "vegan", "tempeh,whole wheat bread,avocado,lettuce", 12, "lunch"],
    ["Vegan Protein Bowl", 580, 26, 20, 68, "vegan", "quinoa,tofu,sweet potato,tahini", 25, "lunch,dinner"],
    ["Lentil Curry", 450, 20, 14, 62, "vegan", "lentils,coconut milk,curry spices", 30, "dinner"],
    ["Grilled Vegetable Salad", 180, 6, 8, 22, "vegan", "zucchini,eggplant,tomato,balsamic", 15, "lunch,salad"],
    ["Cucumber Salad", 85, 2, 4, 10, "vegan", "cucumber,tomato,lemon,herbs", 5, "snack,salad,quick"],
]

columns = ["name","calories","protein","fat","carbs","diet_type","ingredients","prep_time","tags"]
recipes = pd.DataFrame(recipes_data, columns=columns)

# Step 4: Health Assessment & Suggestions Engine
def assess_health_status(weight, height, age, gender, activity_level):
    """Assess user's health status and provide insights"""
    # Calculate BMI
    height_m = height / 100
    bmi = weight / (height_m ** 2)

    # BMI Categories
    if bmi < 18.5:
        bmi_status = "Underweight"
        bmi_risk = "⚠️ May lead to weakened immunity and nutrient deficiencies"
    elif 18.5 <= bmi < 25:
        bmi_status = "Normal"
        bmi_risk = "✅ Healthy weight range"
    elif 25 <= bmi < 30:
        bmi_status = "Overweight"
        bmi_risk = "⚠️ Increased risk of heart disease and diabetes"
    else:
        bmi_status = "Obese"
        bmi_risk = "🚨 High risk - consider medical consultation"

    # Ideal weight range
    ideal_weight_min = 18.5 * (height_m ** 2)
    ideal_weight_max = 24.9 * (height_m ** 2)

    return {
        "bmi": round(bmi, 1),
        "bmi_status": bmi_status,
        "bmi_risk": bmi_risk,
        "ideal_weight_range": (round(ideal_weight_min, 1), round(ideal_weight_max, 1))
    }

def generate_exercise_plan(user_data, health_status):
    """Generate personalized exercise recommendations"""
    exercises = {
        "cardio": [],
        "strength": [],
        "flexibility": [],
        "weekly_schedule": []
    }

    bmi = health_status["bmi"]
    goal = user_data.get("goal", "maintain")
    activity = user_data["activity_level"]

    # Cardio recommendations based on BMI and goal
    if bmi < 18.5:  # Underweight
        exercises["cardio"] = [
            "🚶 Light walking: 20-30 min, 3x/week",
            "🚴 Stationary cycling: 15-20 min, 2x/week (low intensity)",
            "🏊 Swimming: 20 min, 2x/week (builds muscle without high impact)"
        ]
    elif bmi >= 30:  # Obese
        exercises["cardio"] = [
            "🚶 Walking: 30-45 min, 5-6x/week (low impact, joint-friendly)",
            "🚴 Cycling: 20-30 min, 3x/week",
            "💧 Water aerobics: 30 min, 2x/week (excellent for joints)",
            "🏋️ Elliptical: 20-25 min, 2-3x/week (low impact)"
        ]
    elif bmi >= 25:  # Overweight
        exercises["cardio"] = [
            "🏃 Brisk walking/jogging: 30-45 min, 4-5x/week",
            "🚴 Cycling: 30-40 min, 3x/week",
            "🏊 Swimming: 30 min, 2x/week",
            "⛰️ Stair climbing: 15-20 min, 2x/week"
        ]
    else:  # Normal weight
        exercises["cardio"] = [
            "🏃 Running: 30-40 min, 3-4x/week",
            "🚴 HIIT cycling: 20-30 min, 2x/week",
            "🏊 Swimming: 30-45 min, 2x/week",
            "🎾 Sports (tennis, basketball): 45-60 min, 2x/week"
        ]

    # Strength training based on goal
    if goal == "gain" or bmi < 18.5:
        exercises["strength"] = [
            "🏋️ Compound lifts: Squats, Deadlifts, Bench Press (3 sets × 8-12 reps)",
            "💪 Upper body: Pull-ups, Rows, Shoulder Press (3 sets × 8-12 reps)",
            "🦵 Lower body: Lunges, Leg Press, Calf Raises (3 sets × 10-15 reps)",
            "💪 Core: Planks (3 × 30-60 sec), Ab wheel rollouts",
            "📅 Frequency: 4-5 days/week, progressive overload",
            "⏱️ Rest: 60-90 seconds between sets"
        ]
    elif goal == "lose":
        exercises["strength"] = [
            "🏋️ Circuit training: 3 sets × 12-15 reps (minimal rest)",
            "💪 Bodyweight: Push-ups, Squats, Lunges, Burpees",
            "🏋️ Resistance bands: Full body workout",
            "💪 Core circuit: Planks, Mountain climbers, Bicycle crunches",
            "📅 Frequency: 3-4 days/week",
            "⏱️ Rest: 30-45 seconds between exercises"
        ]
    else:  # Maintain
        exercises["strength"] = [
            "🏋️ Full body workout: 3 sets × 10-12 reps",
            "💪 Upper: Bench press, Rows, Overhead press",
            "🦵 Lower: Squats, Deadlifts, Leg curls",
            "💪 Core: Weighted planks, Cable rotations",
            "📅 Frequency: 3 days/week",
            "⏱️ Rest: 45-60 seconds between sets"
        ]

    # Flexibility and recovery
    exercises["flexibility"] = [
        "🧘 Yoga: 20-30 min, 2-3x/week (improves flexibility & reduces stress)",
        "🤸 Dynamic stretching: 10 min before workouts",
        "🧘 Static stretching: 10-15 min after workouts",
        "🎯 Foam rolling: 10 min, 3-4x/week (muscle recovery)",
        "🧘 Meditation: 10-15 min daily (mental health)"
    ]

    # Weekly schedule template
    if activity == "low":
        exercises["weekly_schedule"] = [
            "Monday: 30 min walk + 10 min stretching",
            "Tuesday: Rest or light yoga",
            "Wednesday: 20 min bodyweight exercises + 30 min walk",
            "Thursday: Rest or 20 min yoga",
            "Friday: 30 min walk + 10 min core work",
            "Saturday: 30-45 min outdoor activity (cycling, hiking)",
            "Sunday: Rest day"
        ]
    elif activity == "medium":
        exercises["weekly_schedule"] = [
            "Monday: 30 min cardio + 20 min upper body strength",
            "Tuesday: 30 min yoga or active recovery",
            "Wednesday: 30 min HIIT + 15 min core",
            "Thursday: 30 min cardio + 20 min lower body strength",
            "Friday: Rest or light activity",
            "Saturday: 45 min full body workout or sports",
            "Sunday: 30 min yoga + stretching"
        ]
    else:  # High activity
        exercises["weekly_schedule"] = [
            "Monday: 40 min cardio + 30 min upper body strength",
            "Tuesday: 30 min HIIT + 20 min core",
            "Wednesday: 40 min cardio + 30 min lower body strength",
            "Thursday: Active recovery (yoga, swimming)",
            "Friday: 40 min cardio + 30 min full body circuit",
            "Saturday: 60 min intense workout or sports",
            "Sunday: 30 min yoga + foam rolling"
        ]

    return exercises

def generate_health_suggestions(user_data, health_status, plan):
    """Generate personalized health improvement suggestions"""
    suggestions = []

    # BMI-based suggestions
    if health_status["bmi"] < 18.5:
        suggestions.extend([
            "🎯 Focus on calorie-dense, nutrient-rich foods",
            "💪 Include strength training 3-4x per week to build muscle mass",
            "🥜 Add healthy fats: nuts, avocados, olive oil",
            "🍽️ Eat 5-6 smaller meals throughout the day",
            "💊 Consider a multivitamin supplement (consult doctor)"
        ])
    elif health_status["bmi"] >= 25:
        suggestions.extend([
            "🏃 Increase physical activity to 45-60 min daily",
            "🥗 Focus on high-fiber, low-calorie vegetables",
            "💧 Drink 8-10 glasses of water daily",
            "🍬 Reduce sugar and processed foods",
            "📊 Track your calories and maintain a 300-500 deficit"
        ])
    else:
        suggestions.extend([
            "✅ Maintain your current healthy weight",
            "🏋️ Continue regular exercise routine",
            "🥗 Focus on balanced nutrition"
        ])

    # Activity level suggestions
    if user_data["activity_level"] == "low":
        suggestions.append("🚶 Start with 30 min daily walks and gradually increase")
        suggestions.append("🧘 Try yoga or stretching for flexibility")
    elif user_data["activity_level"] == "medium":
        suggestions.append("💪 Add 2-3 strength training sessions per week")
    else:
        suggestions.append("⚡ Ensure adequate rest and recovery days")
        suggestions.append("🥤 Stay well-hydrated during intense workouts")

    # Goal-specific suggestions
    goal = user_data.get("goal", "maintain")
    if goal == "lose":
        suggestions.extend([
            "📉 Aim for 0.5-1kg weight loss per week (safe rate)",
            "🍽️ Use smaller plates to control portion sizes",
            "😴 Get 7-8 hours of quality sleep",
            "📝 Keep a food journal to track progress"
        ])
    elif goal == "gain":
        suggestions.extend([
            "📈 Aim for 0.25-0.5kg weight gain per week",
            "🥩 Prioritize protein (aim for 2g per kg body weight)",
            "🏋️ Focus on progressive overload in strength training",
            "🍚 Don't skip meals, especially post-workout"
        ])

    # Protein adequacy check
    protein_ratio = plan["totals"]["protein"] / user_data["weight"]
    if protein_ratio < 1.2:
        suggestions.append("⚠️ Increase protein intake - current level may be insufficient")

    # General wellness tips
    suggestions.extend([
        "🧘 Practice stress management (meditation, deep breathing)",
        "🥦 Eat a variety of colorful vegetables daily",
        "☀️ Get 15-20 min of sunlight daily for vitamin D"
    ])

    return suggestions

# Step 5: Enhanced calorie & macro calculation
def calculate_nutrition_targets(weight, height, age, gender, activity_level, goal="maintain"):
    # Mifflin-St Jeor Equation
    if gender.lower() == "male":
        bmr = 10 * weight + 6.25 * height - 5 * age + 5
    else:
        bmr = 10 * weight + 6.25 * height - 5 * age - 161

    activity_multipliers = {"low": 1.2, "medium": 1.55, "high": 1.9}
    tdee = bmr * activity_multipliers.get(activity_level, 1.55)

    # Adjust for goals
    goal_adjustments = {"lose": -500, "maintain": 0, "gain": 300}
    target_calories = tdee + goal_adjustments.get(goal, 0)

    # Calculate macro targets
    protein_target = weight * 2.0
    fat_target = (target_calories * 0.25) / 9
    carbs_target = (target_calories - (protein_target * 4) - (fat_target * 9)) / 4

    return {
        "calories": round(target_calories),
        "protein": round(protein_target),
        "fat": round(fat_target),
        "carbs": round(carbs_target),
        "bmr": round(bmr),
        "tdee": round(tdee)
    }

# Step 6: Advanced meal plan optimization with cuisine filter
def optimize_meal_plan(user_input, recipes_df):
    targets = calculate_nutrition_targets(
        user_input["weight"], user_input["height"], user_input["age"],
        user_input["gender"], user_input["activity_level"], user_input.get("goal", "maintain")
    )

    meals_per_day = user_input.get("meals_per_day", 3)

    # Filter recipes by diet type
    if user_input["diet_type"] != "any":
        allowed = recipes_df[recipes_df["diet_type"] == user_input["diet_type"]].copy()
    else:
        allowed = recipes_df.copy()

    # Filter by cuisine preference
    if user_input.get("cuisine", "any") != "any":
        cuisine_filter = user_input["cuisine"]
        allowed = allowed[allowed["tags"].str.contains(cuisine_filter, case=False, na=False)]

    if len(allowed) < meals_per_day:
        return {"error": f"Not enough recipes for selected diet type and cuisine. Try selecting 'any' cuisine or different diet type."}

    # Categorize meals by tags
    breakfast = allowed[allowed["tags"].str.contains("breakfast")]
    lunch = allowed[allowed["tags"].str.contains("lunch")]
    dinner = allowed[allowed["tags"].str.contains("dinner")]
    snacks = allowed[allowed["tags"].str.contains("snack")]

    # Build meal plan
    selected_meals = []

    if meals_per_day == 2:
        if len(breakfast) > 0 and len(dinner) > 0:
            selected_meals.append(breakfast.sample(1).iloc[0])
            selected_meals.append(dinner.sample(1).iloc[0])
    elif meals_per_day == 3:
        if len(breakfast) > 0 and len(lunch) > 0 and len(dinner) > 0:
            selected_meals.append(breakfast.sample(1).iloc[0])
            selected_meals.append(lunch.sample(1).iloc[0])
            selected_meals.append(dinner.sample(1).iloc[0])
    elif meals_per_day == 4:
        if len(breakfast) > 0 and len(lunch) > 0 and len(dinner) > 0 and len(snacks) > 0:
            selected_meals.append(breakfast.sample(1).iloc[0])
            selected_meals.append(lunch.sample(1).iloc[0])
            selected_meals.append(snacks.sample(1).iloc[0])
            selected_meals.append(dinner.sample(1).iloc[0])
    else:  # 5 meals
        if len(breakfast) > 0 and len(lunch) > 0 and len(dinner) > 0 and len(snacks) >= 2:
            selected_meals.append(breakfast.sample(1).iloc[0])
            selected_meals.append(snacks.sample(1).iloc[0])
            selected_meals.append(lunch.sample(1).iloc[0])
            snack2 = snacks[~snacks["name"].isin([selected_meals[1]["name"]])]
            selected_meals.append(snack2.sample(1).iloc[0] if len(snack2) > 0 else snacks.sample(1).iloc[0])
            selected_meals.append(dinner.sample(1).iloc[0])

    # Calculate totals
    total_cal = sum(m["calories"] for m in selected_meals)
    total_protein = sum(m["protein"] for m in selected_meals)
    total_fat = sum(m["fat"] for m in selected_meals)
    total_carbs = sum(m["carbs"] for m in selected_meals)

    # Calculate accuracy metrics
    cal_accuracy = 100 - abs((total_cal - targets["calories"]) / targets["calories"] * 100)
    protein_accuracy = 100 - abs((total_protein - targets["protein"]) / targets["protein"] * 100)

    return {
        "targets": targets,
        "meals_per_day": meals_per_day,
        "totals": {
            "calories": total_cal,
            "protein": total_protein,
            "fat": total_fat,
            "carbs": total_carbs
        },
        "accuracy": {
            "calories": round(max(0, cal_accuracy), 1),
            "protein": round(max(0, protein_accuracy), 1)
        },
        "meals": selected_meals
    }

# Step 7: Enhanced interactive UI with feedback
age = widgets.IntSlider(value=25, min=10, max=80, step=1, description='Age (yrs):')
gender = widgets.Dropdown(options=['male','female'], description='Gender:')
height = widgets.IntSlider(value=170, min=100, max=210, step=1, description='Height (cm):')
weight = widgets.IntSlider(value=65, min=30, max=150, step=1, description='Weight (kg):')
activity = widgets.Dropdown(options=['low','medium','high'], description='Activity:', value='medium')
diet = widgets.Dropdown(options=['vegetarian','non-vegetarian','vegan','any'], description='Diet Type:', value='any')
goal = widgets.Dropdown(options=['lose','maintain','gain'], description='Goal:', value='maintain')
cuisine = widgets.Dropdown(
    options=['any', 'indian', 'chinese', 'japanese', 'mediterranean', 'italian',
             'mexican', 'thai', 'american', 'korean', 'vietnamese', 'african'],
    description='Cuisine:',
    value='any'
)
meals = widgets.IntSlider(value=3, min=2, max=5, step=1, description='Meals/day:')

generate_button = widgets.Button(description="🎯 Generate Plan", button_style='success',
                                 layout=widgets.Layout(width='200px', height='40px'))
health_button = widgets.Button(description="📊 Health Assessment", button_style='info',
                               layout=widgets.Layout(width='200px', height='40px'))
exercise_button = widgets.Button(description="💪 Exercise Plan", button_style='warning',
                                layout=widgets.Layout(width='200px', height='40px'))
output = widgets.Output()

def on_generate_click(b):
    with output:
        clear_output()
        user_data = {
            "age": age.value,
            "gender": gender.value,
            "height": height.value,
            "weight": weight.value,
            "activity_level": activity.value,
            "diet_type": diet.value,
            "goal": goal.value,
            "meals_per_day": meals.value,
            "cuisine": cuisine.value
        }

        # Generate health assessment
        health_status = assess_health_status(
            user_data["weight"], user_data["height"],
            user_data["age"], user_data["gender"], user_data["activity_level"]
        )

        # Generate meal plan
        plan = optimize_meal_plan(user_data, recipes)

        if "error" in plan:
            print(f"❌ Error: {plan['error']}")
            return

        print("="*70)
        print("🎯  OPTIMIZED PERSONALIZED DIET PLAN WITH HEALTH INSIGHTS")
        print("="*70)

        # Health Status
        print(f"\n💊 HEALTH STATUS")
        print(f"   BMI: {health_status['bmi']} ({health_status['bmi_status']})")
        print(f"   {health_status['bmi_risk']}")
        print(f"   Ideal Weight Range: {health_status['ideal_weight_range'][0]}-{health_status['ideal_weight_range'][1]} kg")

        print(f"\n📊 NUTRITIONAL TARGETS (Daily)")
        print(f"   BMR: {plan['targets']['bmr']} kcal (at rest)")
        print(f"   TDEE: {plan['targets']['tdee']} kcal (with activity)")
        print(f"   Target Calories: {plan['targets']['calories']} kcal")
        print(f"   Protein:  {plan['targets']['protein']}g")
        print(f"   Fat:      {plan['targets']['fat']}g")
        print(f"   Carbs:    {plan['targets']['carbs']}g")

        print(f"\n📈 YOUR MEAL PLAN TOTALS")
        print(f"   Calories: {plan['totals']['calories']} kcal ({plan['accuracy']['calories']}% accurate)")
        print(f"   Protein:  {plan['totals']['protein']}g ({plan['accuracy']['protein']}% accurate)")
        print(f"   Fat:      {plan['totals']['fat']}g")
        print(f"   Carbs:    {plan['totals']['carbs']}g")

        print(f"\n🍽️  YOUR {plan['meals_per_day']} MEALS")
        print("-"*70)

        meal_types = ["Breakfast", "Morning Snack", "Lunch", "Evening Snack", "Dinner"]
        for i, meal in enumerate(plan["meals"]):
            meal_name = meal_types[i] if i < len(meal_types) else f"Meal {i+1}"
            print(f"\n{meal_name}: {meal['name']}")
            print(f"   📊 {meal['calories']} kcal | P: {meal['protein']}g | F: {meal['fat']}g | C: {meal['carbs']}g")
            print(f"   🥗 Type: {meal['diet_type']} | ⏱️  Prep: {meal['prep_time']} mins")
            print(f"   🛒 Ingredients: {meal['ingredients']}")

        # Generate and display suggestions
        suggestions = generate_health_suggestions(user_data, health_status, plan)

        print("\n" + "="*70)
        print("💡 PERSONALIZED HEALTH SUGGESTIONS")
        print("="*70)
        for i, suggestion in enumerate(suggestions[:10], 1):  # Show top 10 suggestions
            print(f"{i}. {suggestion}")

        print("\n" + "="*70)
        print("✅ Your optimized meal plan with health insights is ready!")
        print("💡 Tip: Click 'Health Assessment' for detailed analysis")
        print("🔄 Regenerate for different meal combinations")
        print("="*70)

def on_health_click(b):
    with output:
        clear_output()
        user_data = {
            "age": age.value,
            "gender": gender.value,
            "height": height.value,
            "weight": weight.value,
            "activity_level": activity.value,
            "diet_type": diet.value,
            "goal": goal.value,
            "meals_per_day": meals.value
        }

        health_status = assess_health_status(
            user_data["weight"], user_data["height"],
            user_data["age"], user_data["gender"], user_data["activity_level"]
        )

        plan = optimize_meal_plan(user_data, recipes)
        suggestions = generate_health_suggestions(user_data, health_status, plan)

        print("="*70)
        print("📊  COMPREHENSIVE HEALTH ASSESSMENT")
        print("="*70)

        print(f"\n🔍 BODY COMPOSITION ANALYSIS")
        print(f"   Current Weight: {user_data['weight']} kg")
        print(f"   Height: {user_data['height']} cm")
        print(f"   BMI: {health_status['bmi']} ({health_status['bmi_status']})")
        print(f"   {health_status['bmi_risk']}")
        print(f"   Ideal Weight: {health_status['ideal_weight_range'][0]}-{health_status['ideal_weight_range'][1]} kg")

        weight_diff = user_data['weight'] - health_status['ideal_weight_range'][1]
        if weight_diff > 0:
            print(f"   📉 You are {round(weight_diff, 1)} kg above ideal range")
        elif user_data['weight'] < health_status['ideal_weight_range'][0]:
            diff = health_status['ideal_weight_range'][0] - user_data['weight']
            print(f"   📈 You are {round(diff, 1)} kg below ideal range")
        else:
            print(f"   ✅ You are within healthy weight range!")

        print(f"\n⚡ METABOLIC PROFILE")
        print(f"   Age: {user_data['age']} years")
        print(f"   Gender: {user_data['gender'].capitalize()}")
        print(f"   Activity Level: {user_data['activity_level'].capitalize()}")
        print(f"   BMR: {plan['targets']['bmr']} kcal/day")
        print(f"   TDEE: {plan['targets']['tdee']} kcal/day")
        print(f"   Goal: {user_data['goal'].capitalize()} weight")

        print(f"\n🎯 RECOMMENDED ACTIONS")
        print("-"*70)
        for i, suggestion in enumerate(suggestions, 1):
            print(f"{i}. {suggestion}")

        print("\n" + "="*70)
        print("📅 NEXT STEPS")
        print("="*70)
        print("1. Follow your personalized meal plan consistently")
        print("2. Track your progress weekly (weight, energy levels, mood)")
        print("3. Adjust calorie intake if not seeing desired results after 2 weeks")
        print("4. Stay hydrated - drink at least 8 glasses of water daily")
        print("5. Get 7-9 hours of quality sleep each night")
        print("6. Consider consulting a healthcare provider for detailed assessment")
        print("\n💪 Remember: Sustainable changes take time. Be patient and consistent!")
        print("="*70)

def on_exercise_click(b):
    with output:
        clear_output()
        user_data = {
            "age": age.value,
            "gender": gender.value,
            "height": height.value,
            "weight": weight.value,
            "activity_level": activity.value,
            "diet_type": diet.value,
            "goal": goal.value,
            "meals_per_day": meals.value
        }

        health_status = assess_health_status(
            user_data["weight"], user_data["height"],
            user_data["age"], user_data["gender"], user_data["activity_level"]
        )

        exercise_plan = generate_exercise_plan(user_data, health_status)

        print("="*70)
        print("💪  PERSONALIZED EXERCISE & FITNESS PLAN")
        print("="*70)

        print(f"\n🎯 FITNESS PROFILE")
        print(f"   Current BMI: {health_status['bmi']} ({health_status['bmi_status']})")
        print(f"   Activity Level: {user_data['activity_level'].capitalize()}")
        print(f"   Fitness Goal: {user_data['goal'].capitalize()} weight")

        print(f"\n🏃 CARDIO WORKOUTS")
        print("-"*70)
        for exercise in exercise_plan["cardio"]:
            print(f"   {exercise}")

        print(f"\n🏋️  STRENGTH TRAINING")
        print("-"*70)
        for exercise in exercise_plan["strength"]:
            print(f"   {exercise}")

        print(f"\n🧘 FLEXIBILITY & RECOVERY")
        print("-"*70)
        for exercise in exercise_plan["flexibility"]:
            print(f"   {exercise}")

        print(f"\n📅 WEEKLY WORKOUT SCHEDULE")
        print("-"*70)
        for day_plan in exercise_plan["weekly_schedule"]:
            print(f"   {day_plan}")

        print("\n" + "="*70)
        print("💡 EXERCISE TIPS FOR SUCCESS")
        print("="*70)

        tips = [
            "⏰ Consistency is key - schedule workouts like appointments",
            "📈 Track your progress - note weights, reps, and how you feel",
            "💧 Stay hydrated - drink water before, during, and after workouts",
            "🍽️ Fuel properly - eat protein + carbs within 2 hours post-workout",
            "😴 Prioritize recovery - muscles grow during rest, not during workout",
            "🎵 Make it fun - listen to music or workout with friends",
            "📱 Use fitness apps to track progress and stay motivated",
            "⚠️ Listen to your body - rest if you feel pain or excessive fatigue",
            "🎯 Set SMART goals - Specific, Measurable, Achievable, Relevant, Time-bound",
            "👥 Consider a personal trainer for proper form and motivation"
        ]

        for tip in tips:
            print(f"   {tip}")

        # Goal-specific exercise advice
        print("\n" + "="*70)
        print("🎯 SPECIFIC ADVICE FOR YOUR GOAL")
        print("="*70)

        if user_data["goal"] == "lose":
            print("   🔥 Focus on burning calories through cardio and HIIT")
            print("   💪 Maintain muscle mass with strength training 3x/week")
            print("   ⏱️ Create a calorie deficit: exercise + diet combined")
            print("   📊 Aim for 150-300 minutes of moderate cardio per week")
            print("   🎯 Target heart rate: 60-75% of max (220 - your age)")
        elif user_data["goal"] == "gain":
            print("   🏋️ Prioritize strength training with progressive overload")
            print("   💪 Focus on compound movements for maximum muscle gain")
            print("   🍽️ Eat in calorie surplus, especially post-workout")
            print("   ⏱️ Limit cardio to 2-3x/week to preserve calories")
            print("   😴 Get 8-9 hours of sleep for optimal muscle recovery")
        else:
            print("   ⚖️ Balance cardio and strength training equally")
            print("   🎯 Maintain current fitness level with consistency")
            print("   💪 Challenge yourself progressively to avoid plateaus")
            print("   🧘 Focus on overall wellness and injury prevention")
            print("   🏃 Mix up your routine to keep it interesting")

        print("\n" + "="*70)
        print("⚠️  IMPORTANT REMINDERS")
        print("="*70)
        print("   • Always warm up for 5-10 minutes before exercising")
        print("   • Cool down and stretch after every workout")
        print("   • Start slow if you're new to exercise")
        print("   • Increase intensity gradually to avoid injury")
        print("   • Consult a doctor before starting any new exercise program")
        print("   • Stop immediately if you experience chest pain or dizziness")
        print("\n💪 Ready to transform your health? Let's get started!")
        print("="*70)

generate_button.on_click(on_generate_click)
health_button.on_click(on_health_click)
exercise_button.on_click(on_exercise_click)

# Display UI
display(widgets.VBox([
    widgets.HTML("<h2 style='color: #2E7D32;'>🥗 Advanced AI Diet Plan with Health Coaching</h2>"),
    widgets.HTML("<p style='color: #666;'>Get personalized meal plans with actionable health suggestions</p>"),
    widgets.HBox([age, gender]),
    widgets.HBox([height, weight]),
    widgets.HBox([activity, goal]),
    widgets.HBox([diet, cuisine]),
    widgets.HBox([meals]),
    widgets.HBox([generate_button, health_button, exercise_button]),
    output
], layout=widgets.Layout(padding='20px')))

